#后台访问端口
server:
  port: 10000

spring:


  #mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql8
    url: jdbc:mysql://localhost:3306/cxm_music
    type: com.alibaba.druid.pool.DruidDataSource
  #redis
  redis:
    host: 1.12.54.183
    port: 6379
    password: redis7
    database: 8
    lettuce:
      pool:
        max-active: 8            #最大连接数
        max-idle: 8                #最大空闲连接
        min-idle: 0                #最小空闲连接
        max-wait: 1000ms        #最大连接等待时间
  #RabbitMq
  rabbitmq:
    host: 1.12.54.183
    port: 5672
    username: root
    password: rabbitmq
    virtual-host: /music
  #mongo
  data:
    mongodb:
      host: 1.12.54.183
      port: 27017
      database: cxmMusic
      username: mongo
      password: mongo5

  mvc:
    #swagger接口文档
    pathmatch:
      matching-strategy: ant_path_matcher
    #静态资源访问
    static-path-pattern: /static/**
#mp
mybatis-plus:
  global-config:
    db-config:
      # 逻辑删除字段名
      logic-delete-field: deleted
      # 逻辑删除字面值：未删除为1
      logic-not-delete-value: 1
      # 逻辑删除字面值：删除为0
      logic-delete-value: 0
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#socket.io
socketIO:
  host: 127.0.0.1
  port: 9999
  # 设置最大每帧处理数据的长度，防止他人利用大数据来攻击服务器
  maxFramePayloadLength: 1048576
  # 设置http交互最大内容长度
  maxHttpContentLength: 1048576
  # socket连接数大小（如只监听一个端口boss线程组为1即可）
  bossCount: 1
  workCount: 100
  allowCustomRequests: true
  # 协议升级超时时间（毫秒），默认10秒。HTTP握手升级为ws协议超时时间
  upgradeTimeout: 1000000
  # Ping消息超时时间（毫秒），默认60秒，这个时间间隔内没有接收到心跳消息就会发送超时事件
  pingTimeout: 6000000
  # Ping消息间隔（毫秒），默认25秒。客户端向服务器发送一条心跳消息间隔
  pingInterval: 25000

#文件上传路径
file:
  upload:
    path: src/main/resources/




